import { Toaster } from '@/components/ui/toaster'
import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rugby Win',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr" className='dark'>
      <body className={inter.className}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
